#!/bin/bash

KUBECONFIG=~/demo/test.conf
CLUSTERS=($(kubectl get -o=jsonpath="{.items[*].metadata.name}{'\n'}" cluster -A --kubeconfig=$KUBECONFIG))
NAMESPACES=($(kubectl get -o=jsonpath="{.items[*].metadata.namespace}{'\n'}" cluster -A --kubeconfig=$KUBECONFIG))
CLUSTERCOUNT=${#CLUSTERS[@]}
COUNTER=0

echo -e "Select a cluster to delete: \n"
for CLUSTER in "${CLUSTERS[@]}"
do
    echo "$COUNTER - CLUSTER NAME: $CLUSTER in NAMESPACE ${NAMESPACES[${COUNTER}]}"
    COUNTER=$((COUNTER+1))
done
echo -e "\n"
read choice

CLUSTER_TO_DELETE=${CLUSTERS[${choice}]}
WORKSPACE_ID=${NAMESPACES[${choice}]}

POD=$(kubectl get po -n kommander | grep auth-mgmt | cut -d " " -f 1 )
KOMMANDER_PROFILE_NAME=$(kubectl logs -n kommander $POD | grep -i cookie | tail -1 | grep -oP "name=\K(.*?)(?=;)")
COOKIE_SUBSTR=$(kubectl logs -n kommander $POD | grep -i cookie | tail -1 | grep -oP "forward_auth=\K(.*?)(?=])")
COOKIE="_forward_auth=${COOKIE_SUBSTR}"
HOST=$(kubectl get KommanderCluster -n kommander -o yaml | grep prometheus | grep -oP "prometheus: \K(.*)$")
ENDPOINT="https://${HOST}/dkp/kommander/dashboard/graphql"
DATA_RAW=$"{\"operationName\":\"ForceRemoveCluster\",\"variables\":{\"id\":\"$CLUSTER_TO_DELETE\",\"workspaceId\":\"$WORKSPACE_ID\"},\"query\":\"mutation ForceRemoveCluster(\$id: String\u0021, \$workspaceId: String\u0021) {\\n  forceRemove(id: \$id, workspaceId: \$workspaceId) {\\n    message\\n    __typename\\n  }\\n}\\n\"}"

echo $DATA_RAW
                      
curl "$ENDPOINT" \
  -H "accept: application/json" \
  -H "content-type: application/json" \
  -H "cookie: $COOKIE" \
  -H "sec-gpc: 1" \
  -H "accept-language: en-GB,en-US;q=0.9,en;q=0.8" \
  -H "sec-fetch-dest: empty" \
  -H "sec-fetch-mode: cors" \
  -H "sec-fetch-site: same-origin" \
  -d $DATA_RAW \
  --compressed \
  --insecure  
