#!/bin/bash

CLUSTER_TO_DELETE='whitehouse-in-cluster2'
WORKSPACE_ID="innovation-z7tqg"
COOKIE="MTY0NDc0NjM1M3xVdjNIX1FNOHZTQVJibWlUVkdVdkhCdmZxTU91WGNpNjVGdnB5VlFNTEg3aWNUclNQSGJVZk1TTDJTVHZPdmx3eVpxR0NILUoxNUlxajhwUEc1NlJvMndzRDNyU1RfbzJVb21XXzhqaU5ON19UQy1sdERjaFM1ejlLN3JxSm1rVjVjMjlkR3kteTZLMy1iYTBGVzlwZnBBaXpmdTY0Um89fGFOXq5Pyv8jzW2hR76eiCL9RPqSuCqaNFp7IoTnDsVd"

[[ ! -z "$KUBECONFIG" ]] && CURRENT_CONFIG=$KUBECONFIG || CURRENT_CONFIG="$HOME/.kube/config"
ENDPOINT=$(CAT $CURRENT_CONFIG | grep https | sed 's/ //g' | sed 's/:6443//g' | sed 's/server://g')/dkp/kommander/dashboard/graphql
echo $ENDPOINT

PROFILE_NAME=$(kubectl -n kommander get secret dkp-credentials -o go-template='{{.data.username|base64decode}}')
echo $PROFILE_NAME


curl ${ENDPOINT} \
  -H 'accept: application/json' \
  -H 'content-type: application/json' \
  -H 'cookie: kommander_profile_name=${PROFILE_NAME}; _forward_auth=${COOKIE}' \
  -H 'sec-gpc: 1' \
  --data-raw $'{"operationName":"ForceRemoveCluster","variables":{"id":${CLUSTER_TO_DELETE},"workspaceId":${WORKSPACE_ID},"query":"mutation ForceRemoveCluster($id: String\u0021, $workspaceId: String\u0021) {\\n  forceRemove(id: $id, workspaceId: $workspaceId) {\\n    message\\n    __typename\\n  }\\n}\\n"}' \
  --compressed \
  --insecure
